const C=window.TOONFLIX_CONFIG,DB=C.FIREBASE_DB_URL.replace(/\/$/,'');let token=sessionStorage.getItem('tf_id')||'',refresh=sessionStorage.getItem('tf_refresh')||'',editing=null,library=[];const $=id=>document.getElementById(id);
function msg(id,t,ok=false){$(id).textContent=t;$(id).style.color=ok?'#7ee2a8':'#ff8ba9'}
function authQuery(){return token?`?auth=${encodeURIComponent(token)}`:''}
async function login(){try{if(!C.FIREBASE_API_KEY||C.FIREBASE_API_KEY.includes('PASTE_'))throw Error('Add your Firebase Web API Key in config.js first.');const r=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=${encodeURIComponent(C.FIREBASE_API_KEY)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value.trim(),password:$('password').value,returnSecureToken:true})});const d=await r.json();if(!r.ok)throw Error(d.error?.message||'Login failed');token=d.idToken;refresh=d.refreshToken;sessionStorage.setItem('tf_id',token);sessionStorage.setItem('tf_refresh',refresh);showApp();load()}catch(e){msg('loginMsg',e.message)}}
function showApp(){$('login').classList.add('hidden');$('app').classList.remove('hidden')}
function reset(){editing=null;$('formTitle').textContent='Add anime';['aTitle','aPoster','aGenre','aSynopsis'].forEach(x=>$(x).value='');$('aYear').value='';$('aRating').value='';$('aFormat').value='TV';$('aSubDub').value='Hindi Dub';$('epRows').innerHTML='';addEp()}
function addEp(url='',type='auto'){const n=$('epRows').children.length+1;const d=document.createElement('div');d.className='ep-row';d.innerHTML=`<span>EP ${n}</span><input class="epurl" placeholder="Stream/embed URL" value="${url.replace(/"/g,'&quot;')}"><select class="eptype"><option ${type==='auto'?'selected':''}>auto</option><option ${type==='video'?'selected':''}>video</option><option ${type==='embed'?'selected':''}>embed</option></select><button type="button">×</button>`;d.querySelector('button').onclick=()=>{d.remove();renum()};$('epRows').appendChild(d)}
function renum(){[...$('epRows').children].forEach((x,i)=>x.children[0].textContent='EP '+(i+1))}
async function api(path,opts={}){const r=await fetch(DB+path+authQuery(),opts);if(!r.ok){const d=await r.json().catch(()=>({}));throw Error(d.error||`Firebase error ${r.status}`)}return r.json()}
async function save(){try{const title=$('aTitle').value.trim();if(!title)throw Error('Anime title is required.');const eps=[...document.querySelectorAll('.ep-row')].map(x=>({url:x.querySelector('.epurl').value.trim(),type:x.querySelector('.eptype').value})).filter(x=>x.url);const data={title,poster:$('aPoster').value.trim(),genre:$('aGenre').value.trim(),year:Number($('aYear').value)||null,rating:Number($('aRating').value)||null,format:$('aFormat').value,subDub:$('aSubDub').value,synopsis:$('aSynopsis').value.trim(),episodesData:eps,episodes:eps.length,updatedAt:Date.now(),createdAt:editing?.createdAt||Date.now()};const path=editing?`/anime/${encodeURIComponent(editing.id)}.json`:'/anime.json';await api(path,{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});msg('saveMsg','Saved successfully.',true);reset();load()}catch(e){msg('saveMsg',e.message)}}
async function load(){try{const d=await api('/anime.json');library=d?Object.entries(d).map(([id,v])=>({id,...v})):[];library.sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));renderLibrary()}catch(e){msg('saveMsg',e.message)}}
function renderLibrary(){const q=$('filter').value.toLowerCase();const list=library.filter(a=>(a.title||'').toLowerCase().includes(q));$('library').innerHTML=list.map(a=>`<div class="admin-item"><img src="${esc(a.poster||'')}" alt=""><div><h3>${esc(a.title||'Untitled')}</h3><div class="card-meta">${esc(a.genre||'Anime')} · ${a.year||'—'} · ${a.episodes||0} eps</div></div><div class="admin-actions"><button class="secondary" onclick="editAnime('${a.id}')">Edit</button><button class="danger" onclick="delAnime('${a.id}')">Delete</button></div></div>`).join('')||'<div class="empty">No anime.</div>'}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
window.editAnime=id=>{const a=library.find(x=>x.id===id);if(!a)return;editing=a;$('formTitle').textContent='Edit anime';$('aTitle').value=a.title||'';$('aPoster').value=a.poster||'';$('aGenre').value=a.genre||'';$('aYear').value=a.year||'';$('aRating').value=a.rating||'';$('aFormat').value=a.format||'TV';$('aSubDub').value=a.subDub||'Hindi Dub';$('aSynopsis').value=a.synopsis||'';$('epRows').innerHTML='';(a.episodesData||[]).forEach(e=>addEp(typeof e==='string'?e:e.url||'',typeof e==='string'?'auto':e.type||'auto'));window.scrollTo({top:0,behavior:'smooth'})}
window.delAnime=async id=>{const a=library.find(x=>x.id===id);if(!a||!confirm(`Delete "${a.title}"?`))return;try{await api(`/anime/${encodeURIComponent(id)}.json`,{method:'DELETE'});load()}catch(e){msg('saveMsg',e.message)}}
$('loginBtn').onclick=login;$('password').onkeydown=e=>{if(e.key==='Enter')login()};$('logout').onclick=()=>{sessionStorage.clear();location.reload()};$('newAnime').onclick=reset;$('cancel').onclick=reset;$('addEp').onclick=()=>addEp();$('save').onclick=save;$('refresh').onclick=load;$('filter').oninput=renderLibrary;
if(token)showApp();reset();if(token)load();